In [1]:
import pandas as pd
import numpy as np
from ollama import chat

In [2]:
# Loading the Data from the CSV file
file = pd.read_csv('/Users/abhishekchauhan/Work/NetImpact/july 9 work/processed_files_proja_1577555378000_twitter_2026_7_kotak_news_pattern_file_tag.csv')
file

,comment_text,cluster_name,cluster_tags,sentiment_name,sentiment_tags,comments_count,likes,impression,shares,link,user_name,date_time,followers
0,NaN,NaN,NaN,Neutral,NaN,1,0,0,0,NaN,Kotak/Jun/News/1124,NaN,0
1,145 करोड़ रुपये के नगर निगम-बैंक साठगांठ धोखाध...,NaN,NaN,Negative,आरोप,1,0,0,0,NaN,Kotak/Jun/News/3845,NaN,0
2,15 arrested for mule accounts operation in Dur...,Negative proj A,"fraud, cheating, illegal",Negative,"fraud , police , cheating , fraud",1,0,0,0,NaN,Kotak/Jun/News/2058,NaN,0
3,"17,000 रुपये तक सस्ता हुआ OnePlus 13! मिलता है...",NaN,NaN,Neutral,NaN,1,0,0,0,NaN,Kotak/Jun/News/3329,NaN,0
4,29 June Current Affairs: India's first govt ca...,Positive Proj A,"like, safe",Negative,services+down,1,0,0,0,NaN,Kotak/Jun/News/482,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,हरियाणा 150 करोड़ कोटक महिंद्रा बैंक घोटाला:बॉम...,NaN,NaN,Negative,"आरोप , विवाद",1,0,0,0,NaN,Kotak/Jun/News/2891,NaN,0
870,हरियाणा IAS ने दुबई अकाउंट में भेजे ₹2.5 करोड़...,NaN,NaN,Negative,आरोप,1,0,0,0,NaN,Kotak/Jun/News/1461,NaN,0
871,हरियाणा IDFC बैंक घोटाला: ऑडियो टेप से फंसे IA...,Negative proj A,scam,Negative,आरोप,1,0,0,0,NaN,Kotak/Jun/News/979,NaN,0
872,होम लोन ओवरड्राफ्ट क्या है और कैसे लें इसका फा...,NaN,NaN,Neutral,NaN,1,0,0,0,NaN,Kotak/Jun/News/2701,NaN,0
873,റിലയൻസ് ഡിജിറ്റൽ ഓഫറുകൾ അവസാനിക്കാൻ മണിക്കൂറുക...,NaN,NaN,Neutral,NaN,1,0,0,0,NaN,Kotak/Jun/News/417,NaN,0

In [3]:
# Assign Negative values where cluster_name = Negative proj A
file['Sentiment Pattern'] = np.where(
    file['cluster_name'].eq('Negative proj A'),
    'Negative',
    None
)

In [4]:
file['Sentiment Pattern']

0          None
1          None
2      Negative
3          None
4          None
         ...
869        None
870        None
871    Negative
872        None
873        None
Name: Sentiment Pattern, Length: 874, dtype: object

In [5]:
file['Sentiment Pattern'].value_counts()

Sentiment Pattern
Negative    442
Name: count, dtype: int64

In [6]:
# Assign Negative values where Sentiment_name = Negative

file['Sentiment Pattern']= np.where(
    file['sentiment_name'].eq('Negative'),
    'Negative',
    file['Sentiment Pattern']
)

In [7]:
file['Sentiment Pattern']

0          None
1      Negative
2      Negative
3          None
4      Negative
         ...
869    Negative
870    Negative
871    Negative
872        None
873        None
Name: Sentiment Pattern, Length: 874, dtype: object

In [8]:
file['Sentiment Pattern'].value_counts()

Sentiment Pattern
Negative    618
Name: count, dtype: int64

In [9]:
# Creating the New DataFrame
New_file_Data = file.copy()

In [10]:
New_file_Data = New_file_Data[(New_file_Data['Sentiment Pattern']=='Negative')]

In [11]:
New_file_Data

,comment_text,cluster_name,cluster_tags,sentiment_name,sentiment_tags,comments_count,likes,impression,shares,link,user_name,date_time,followers,Sentiment Pattern
1,145 करोड़ रुपये के नगर निगम-बैंक साठगांठ धोखाध...,NaN,NaN,Negative,आरोप,1,0,0,0,NaN,Kotak/Jun/News/3845,NaN,0,Negative
2,15 arrested for mule accounts operation in Dur...,Negative proj A,"fraud, cheating, illegal",Negative,"fraud , police , cheating , fraud",1,0,0,0,NaN,Kotak/Jun/News/2058,NaN,0,Negative
4,29 June Current Affairs: India's first govt ca...,Positive Proj A,"like, safe",Negative,services+down,1,0,0,0,NaN,Kotak/Jun/News/482,NaN,0,Negative
5,₹3.8 Crore Loan Fraud Unearthed At Kotak Mahin...,Negative proj A,fraud,Negative,"fraud , fraud, complaint , police , fir",1,0,0,0,NaN,Kotak/Jun/News/507,NaN,0,Negative
6,5 Mistakes Home Loan Customers MakeFrom overst...,Negative proj A,"not+help, mistake",Negative,"penal , mistake",1,0,0,0,NaN,Kotak/Jun/News/3196,NaN,0,Negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867,हरदोई में पैन कार्ड से 11 लाख की धोखाधड़ी:7 बै...,Negative proj A,scam,Negative,"धोखा , खराब",1,0,0,0,NaN,Kotak/Jun/News/1419,NaN,0,Negative
868,हरियाणा 150 करोड़ कोटक महिंद्रा बैंक घोटाला:बॉम...,NaN,NaN,Negative,"police , आरोप , विवाद",1,0,0,0,NaN,Kotak/Jun/News/2892,NaN,0,Negative
869,हरियाणा 150 करोड़ कोटक महिंद्रा बैंक घोटाला:बॉम...,NaN,NaN,Negative,"आरोप , विवाद",1,0,0,0,NaN,Kotak/Jun/News/2891,NaN,0,Negative
870,हरियाणा IAS ने दुबई अकाउंट में भेजे ₹2.5 करोड़...,NaN,NaN,Negative,आरोप,1,0,0,0,NaN,Kotak/Jun/News/1461,NaN,0,Negative
871,हरियाणा IDFC बैंक घोटाला: ऑडियो टेप से फंसे IA...,Negative proj A,scam,Negative,आरोप,1,0,0,0,NaN,Kotak/Jun/News/979,NaN,0,Negative

In [12]:
# Top 100 rows of Data
pivot_count = pd.DataFrame(New_file_Data['comment_text'].value_counts().reset_index().head(100))

In [13]:
pivot_count['comment_text'].head(5)

0    Navrachana University: The Quiet Architecture ...
1    RBI move sparks race among banks to raise FCNR...
2    How to Save on Movie Tickets Using Credit Card...
3    Navrachana University: The Quiet Architecture ...
4    Finance Minister Nirmala Sitharaman, RSS Sarsa...
Name: comment_text, dtype: object

In [14]:
!ollama list

]11;?\NAME                ID              SIZE      MODIFIED
gemma4:cloud        b06ba4be71c0    -         4 days ago
gemma3:1b           8648f39daa8f    815 MB    3 months ago
deepseek-r1:1.5b    e0979632db5a    1.1 GB    8 months ago
mistral:latest      f974a74358d6    4.1 GB    13 months ago
llama3.2:3b         a80c4f17acd5    2.0 GB    13 months ago
llama3.2:latest     a80c4f17acd5    2.0 GB    14 months ago

In [15]:
SYSTEM_PROMPT = """Role: Kotak Bank Data Extraction Bot only. Extract and categorize Kotak Bank-related feedback from noisy, multilingual, or social media text.
Strict Output Rules:

No intro, conclusion, or emotional response.
Ignore: political statements, religious text, Hindi/Punjabi text, Twitter handles, unrelated hashtags.
Focus only on the banking grievance buried in the text.
ALL output must be in English only, regardless of input language.
Every response must follow the exact 3-line output template below.

Sentiment Logic:

Negative: Bank directly criticized, blamed, or held responsible. Includes: staff/property harmed; bank failure, error, or negligence — even if reported by third party, shared as news, or posted humorously. Journalistic tone does NOT override Negative if Kotak's systems, accounts, or data were directly breached or exploited. Kotak account used as destination for fraudulent transfers — Negative.
Neutral: Polite request, calm issue report, or information sharing with no emotional distress. News/RBI data/industry analysis are Neutral ONLY IF Kotak is not implicated in a failure, breach, named partnership, or customer-facing feature credit. Educational content is Neutral UNLESS Kotak is explicitly named as partner or credited with offering a specific feature/service. Content about other banks where Kotak is not named is always Neutral. Kotak group entities (Education Foundation, Life, Securities, AMC, etc.) are always Neutral unless Kotak Mahindra Bank is directly named. External job postings always Neutral. Individual associated with Kotak attending event in personal capacity where Kotak Bank not named — always Neutral.
Positive: Customer praise, cashback/promotion offers, sponsorships, named partnerships, explicit credit for offering a customer-facing product/feature/service, or internal promotions/leadership elevations. Kotak named in a multi-bank list as actively offering a feature/service or acting as lending/finance supporter — Positive. Educational/informational framing does NOT override Positive if Kotak is directly named as provider. Kotak executive/leader featured or speaking at industry event in official Kotak capacity — Positive. Named partnerships and service credits always override news/press release/educational framing. Kotak group subsidiaries do NOT qualify unless Kotak Mahindra Bank is directly named. External job postings never Positive.

Key Rules:

Polite help request — even about a problem — is Neutral, not Negative.
Negative only when Kotak is directly blamed, staff/property harmed, or incident reflects Kotak's failure/negligence — regardless of tone or who posts.
Positive only for praise, offers, sponsorships, named partnerships, service credits, official event representation, or internal promotions/leadership elevations. External hiring never Positive.
KOTAK-ONLY RULE: Incidents involving only other banks where Kotak is not named are always Neutral.
NAMED PARTNERSHIP RULE: Kotak explicitly named as lending/ecosystem/finance partner — Positive, even if framed as news, press release, or informational article. Being listed among multiple banks as named supporter or lender counts as a named partnership.
MULTI-BANK LIST RULE: Kotak named among banks actively supporting, financing, or partnering on a program — Positive even alongside other banks. Presence of other banks does not dilute Kotak's named role.
FEATURE/SERVICE LISTING RULE: Article naming Kotak as actively offering a product/feature/service — Positive regardless of framing.
LANGUAGE RULE: Input may be Hindi, multilingual, or mixed script. Apply all rules equally regardless of language. ALL output must be in English only.
KOTAK GROUP ENTITY RULE: Kotak Education Foundation, Life, Securities, AMC and other subsidiaries are NOT Kotak Mahindra Bank. Always Neutral unless Kotak Mahindra Bank is directly involved.
JOB POSTING RULE: External job openings always Neutral. Internal promotions/leadership elevations always Positive.
INDIVIDUAL PERSON RULE: Kotak executive speaking at industry event in official Kotak capacity — Positive. Personal capacity where Kotak Bank not named — Neutral.
FRAUD DESTINATION RULE: Kotak account used as destination for fraudulent transfers — Negative, even if fraud was committed by a third party.

Examples:

"Please help me recover my money" → Neutral
"My money is gone and no one is helping" → Negative
"Bank offering cashback on Samsung Galaxy" → Positive
"CBI raids builder-bank nexus" → Neutral (Kotak not blamed)
"RBI data shows credit grew 16% in FY26" → Neutral (market report)
"Bank stole my money, never responded" → Negative
"Thank you for resolving my issue quickly" → Positive
"Bank officer attacked during loan recovery" → Negative (staff harmed)
"Customer got ₹3.21 lakh compensation, bank ignored card closure" → Negative (bank negligence)
"Bank sponsors large music event" → Positive
"Press release on zero-balance vs savings account features" → Neutral (Kotak not named as provider)
"Fraudsters used AI biometrics to access Kotak accounts" → Negative (Kotak systems breached)
"HDFC Bank fined by RBI for KYC violations" → Neutral (other entity)
"FinBox AI lending platform names Kotak as ecosystem partner" → Positive (named partnership)
"Kotak Education Foundation launches scholarship for 1,000 students" → Neutral (group entity)
"Kotak Mahindra Bank hiring Legal Manager in Chennai" → Neutral (external job posting)
"Uday Kotak attends GIFT City meeting" → Neutral (personal capacity, Kotak Bank not named)
"Kotak's collections leader featured as speaker at industry summit" → Positive (official Kotak capacity)
"Article listing Kotak among banks offering UPI cardless ATM withdrawal" → Positive (named provider; framing does not override)
"Kotak promotes Bhavna Chawla and Celia D'Souza to senior marketing leadership" → Positive (internal promotion)
"Hindi article listing ICICI, HDFC, Axis, Kotak, Bajaj Finserv as EV BaaS loan supporters" → Positive (MULTI-BANK LIST RULE + NAMED PARTNERSHIP RULE; language does not override)
"Victim transferred money via NEFT to Kotak branch account in supply scam, goods never received" → Negative (FRAUD DESTINATION RULE)

Output Template:
Mini Summary: [One sentence in English summarizing the core banking incident only]
Sentiment: [Positive / Neutral / Negative]
Cluster: [5–7 words max. Factual phrase naming the banking product and core incident.]
Cluster Rules:

Max 7 words. No exceptions.
Factual phrase — not a category label.
Always name the banking product (Locker, Account, Card, Loan, OTP, ATM, UPI, NEFT, etc.) and core problem or feature.
Strip political blame, government names, religious content, unrelated context.
If about promotions, rewards, or deals — Cluster must include the word "Offers".
Never pad with the bank name.
If fraud/looting alleged without specific product, reflect that accusation directly.
EMPLOYEE NAME RULE: Specific employee named — use their name instead of "officer/staff". Multiple named — use first names only within 7-word limit.

Cluster Examples:

Good: "Mobile number misused for loan OTPs"
Good: "2 crore gold stolen from bank locker"
Good: "Fake Aadhaar used to access account"
Good: "Accidental transfer to wrong account"
Good: "Credit card cashback offers not applied"
Good: "Bank accused of looting customer money"
Good: "Cashback offers on Samsung"
Good: "Rahul Sharma attacked during loan recovery" → if single name
Good: "Bhavna and Celia promoted to marketing leadership" → if multiple names
Good: "Bank sponsors large music event"
Good: "AI biometrics used to breach accounts"
Good: "NEFT fraud via Kotak account"
Good: "Bank named as EV BaaS loan partner"
Bad: "Bank Locker Issue" / "Fraud Problem" / "Bank account fraud loss" / "EV financing support banks listing"'

"""

In [16]:
result = []

for i in pivot_count['comment_text']:
    response = chat(
        model='gemma4:cloud',
        messages=[{"role": "system", "content": SYSTEM_PROMPT},
                {'role': 'user', 'content': i}],
    )
    result.append(response.message.content)

In [17]:
print(result)

["Mini Summary: Graduates from Navrachana University's School of Business and Law have secured placements at Kotak Bank.\nSentiment: Positive\nCluster: Placements at Kotak Bank", 'Mini Summary: Kotak Mahindra Bank is offering interest rates between 6% and 6.15% on FCNR(B) deposits.\nSentiment: Positive\nCluster: FCNR(B) deposit interest rate offers', 'Mini Summary: Kotak Mahindra Bank offers a Buy 1 Get 1 deal on PVR INOX movie tickets for Cashback+ Credit Card holders.\nSentiment: Positive\nCluster: Cashback+ Credit Card movie ticket offers', 'Mini Summary: Graduates from Navrachana University have secured positions at Kotak Bank.\nSentiment: Positive\nCluster: Student placements in Kotak Bank', 'Mini Summary: Nilesh Shah, Managing Director of Kotak Mahindra Asset Management, is listed as a panelist for the Mindmine Summit 2026.\nSentiment: Neutral\nCluster: Kotak Mahindra Asset Management executive attending summit', 'Mini Summary: Kotak Mahindra Bank introduces multiple color options for the Kotak811 Infinity Metal Debit Card along with premium benefits.\nSentiment: Positive\nCluster: Metal Debit Card colors and offers', "Mini Summary: Kotak Institutional Equities report analyzes India's banking sector asset quality and loan growth outlook.\nSentiment: Neutral\nCluster: Banking sector asset quality report", "Mini Summary: Abhishek Bisen from Kotak Mahindra AMC provides expert analysis and positive feedback on the RBI's monetary policy.\nSentiment: Neutral\nCluster: Fixed Income expert analysis on RBI policy", 'Mini Summary: Nilesh Shah, Managing Director of Kotak Mahindra Asset Management, is a panelist at the Mindmine Summit 2026.\nSentiment: Neutral\nCluster: Nilesh Shah attending Mindmine Summit 2026', 'Mini Summary: Kotak Mahindra Bank partners with NSRCEL to provide long-cycle support for women entrepreneurs through the Women Startup Program.\nSentiment: Positive\nCluster: Women Startup Program entrepreneurship support partnership', 'Mini Summary: Chief Economist Upasna Bhardwaj provides analysis and expectations on RBI Monetary Policy.\nSentiment: Positive\nCluster: Upasna Bhardwaj speaking in official capacity', "Mini Summary: Abhishek Bisen from Kotak Mahindra AMC provided expert analysis on the RBI's monetary policy.\nSentiment: Neutral\nCluster: Kotak Mahindra AMC expert analysis on RBI", 'Mini Summary: Kotak Mahindra Bank is offering FCNR(B) deposit rates between 6 per cent and 6.15 per cent.\nSentiment: Positive\nCluster: FCNR(B) deposit rates offering', 'Mini Summary: Kotak Mahindra Bank is offering interest rates between 6% and 6.15% on FCNR(B) deposits.\nSentiment: Positive\nCluster: FCNR(B) deposit interest rate offers', 'Mini Summary: Kotak Mahindra Bank is offering interest rates between 6% and 6.15% on FCNR(B) deposits.\nSentiment: Positive\nCluster: FCNR(B) deposit interest rate offers', 'Mini Summary: Kotak Mahindra Bank reported a 0% Credit-Deposit Ratio in Tripura, indicating virtually no lending in the state.\nSentiment: Neutral\nCluster: Account lending and Credit-Deposit Ratio performance', 'Mini Summary: Multiple bank accounts were used as mule accounts to route funds for an illegal cricket betting and cyber fraud network.\nSentiment: Neutral\nCluster: Bank accounts used for betting fraud', 'Mini Summary: Kotak Institutional Equities provides a positive outlook on the banking sector and leadership changes at HDFC Bank.\nSentiment: Neutral\nCluster: Brokerage analysis of banking sector performance', 'Mini Summary: Kotak Mahindra Bank is offering interest rates between 6% and 6.15% on FCNR(B) deposits.\nSentiment: Positive\nCluster: FCNR(B) deposit interest rate offers', 'Mini Summary: Tushar Verma, who previously held senior positions at Kotak Mahindra Bank, has been appointed as VP at PeepalCo.\nSentiment: Neutral\nCluster: Tushar Verma previous employment at bank', 'Mini Summary: Nilesh Shah from Kotak Mahindra Asset Management is participating as a panelist at the Mindmine Summit 2026.\nSentiment: Neutral\nCluster: Nilesh Shah attending Mindmine Summit event', 'Mini Summary: Kotak Mahindra Bank offers a Buy 1 Get 1 deal on PVR INOX movie tickets for Cashback+ Credit Card holders.\nSentiment: Positive\nCluster: Cashback+ Credit Card movie ticket offers', 'Mini Summary: EduMEasy received a 15 lakh grant through the Kotak BizLabs program.\nSentiment: Positive\nCluster: Kotak BizLabs grant for EdTech innovation', 'Mini Summary: Ruchira Bhardwaja and T Mark Fernandes of Kotak Life attended the People Matters BFSI Talent & Tech Summit 2026.\nSentiment: Neutral\nCluster: Kotak Life representatives attend industry summit', 'Mini Summary: Nilesh Shah of Kotak Mahindra Asset Management is a panelist at the Mindmine Summit 2026.\nSentiment: Neutral\nCluster: Kotak Mahindra AMC leader attending summit', 'Mini Summary: Nilesh Shah of Kotak Mahindra Asset Management Co. Ltd. spoke at the Chamber of Tax Consultants centenary celebration.\nSentiment: Neutral\nCluster: Kotak Asset Management executive attending CTC event', "Mini Summary: Kotak Institutional Equities released a report on the Indian banking sector's asset quality and loan growth outlook.\nSentiment: Neutral\nCluster: Banking sector asset quality and loan report", 'Mini Summary: Nilesh Shah, Managing Director of Kotak Mahindra Asset Management, is a panellist at the Mindmine Summit 2026.\nSentiment: Neutral\nCluster: Nilesh Shah attending Mindmine Summit 2026', 'Mini Summary: Former Kotak Mahindra Bank VP Pushpinder Singh arrested by ED for alleged municipal fund embezzlement and fraud.\nSentiment: Negative\nCluster: Pushpinder Singh arrested for fund embezzlement fraud', 'Mini Summary: Kotak Securities provides technical support and resistance levels for MCX Gold August futures.\nSentiment: Neutral\nCluster: Kotak Securities gold price technical analysis', 'Mini Summary: Kotak Mahindra Bank is identified as having scope to scale up lending activities in Tripura.\nSentiment: Positive\nCluster: Bank named as lending outreach provider', "Mini Summary: Kotak Mahindra Bank is listed as an industry partner for ITM Skills Academy's professional training and placement program.\nSentiment: Positive\nCluster: Bank named as training industry partner", 'Mini Summary: Kotak811 Metal Debit Card is now available in multiple colors with various premium benefits.\nSentiment: Positive\nCluster: Metal Debit Card personalization and offers', 'Mini Summary: Kotak Mahindra Bank offers personalized color options and premium benefits for the Kotak811 Metal Debit Card.\nSentiment: Positive\nCluster: Metal Debit Card color and cashback offers', 'Mini Summary: Kotak Mahindra Bank acted as a recruiter for graduates of Jaipuria Institute of Management.\nSentiment: Positive\nCluster: Bank providing recruitment and job offers', 'Mini Summary: Kotak Mahindra Bank data is being fetched with a two-minute delay.\nSentiment: Negative\nCluster: Data fetch delay in banking systems', "Mini Summary: Kotak Mahindra Capital is acting as a lead manager for Kuku Technologies' IPO.\nSentiment: Positive\nCluster: Lead manager for Kuku Technologies IPO", "Mini Summary: Kotak Mahindra Capital is appointed as an investment banker for Razorpay's IPO.\nSentiment: Positive\nCluster: Investment banking services for Razorpay IPO", 'Mini Summary: Deepak Agrawal of Kotak Mahindra AMC provides a reaction to the RBI MPC outcome and policy repo rate decision.\nSentiment: Neutral\nCluster: Kotak Mahindra AMC reaction to RBI MPC', "Mini Summary: Kotak is appointed as an investment bank to manage Kuku's IPO.\nSentiment: Positive\nCluster: Investment bank for Kuku IPO", 'Mini Summary: Funds were transferred from a Kotak Mahindra Bank account to another bank as part of a larger embezzlement scam involving government officials.\nSentiment: Neutral\nCluster: Account transfer during government fund embezzlement scam', "Mini Summary: Kotak Mahindra Capital is acting as a lead manager for Kuku Technologies' proposed IPO.\nSentiment: Positive\nCluster: Lead manager for Kuku Technologies IPO", 'Mini Summary: 360 ONE Capital lists Kotak Mahindra Bank as a top pick among private sector banks.\nSentiment: Positive\nCluster: Kotak named as top pick bank', 'Mini Summary: Kotak Mahindra Bank increased its workforce from 66,473 to 79,900 employees between 2022 and 2026.\nSentiment: Neutral\nCluster: Staff numbers increase in bank accounts', 'Mini Summary: RBI holiday list mentions Kotak Mahindra Bank will be closed on the fourth Saturday of June 2026.\nSentiment: Neutral\nCluster: Bank branch closure on fourth Saturday', 'Mini Summary: Kotak Mahindra Bank is listed as a provider of home loans under the PMAY scheme.\nSentiment: Positive\nCluster: Bank named as PMAY home loan partner', 'Mini Summary: Kotak Mahindra Bank is listed as a provider of home loans with starting interest rates of 7.60%.\nSentiment: Positive\nCluster: Home loan interest rate offerings', 'Mini Summary: Kotak Mahindra Bank is listed as a provider of home loans with interest rates starting from 7.60 percent.\nSentiment: Positive\nCluster: Home loan interest rates offered', 'Mini Summary: Kotak Mahindra Bank is hiring a Legal Manager for Two Wheeler Finance in Bangalore.\nSentiment: Neutral\nCluster: External job posting for Legal Manager', 'Mini Summary: Bank officials allegedly colluded to manipulate account contact details to facilitate financial fraud.\nSentiment: Negative\nCluster: Pushpender and Dilip manipulated account contact details', 'Mini Summary: Kotak India Growth Fund II settled with SEBI over a five-year delay in winding up and distributing proceeds.\nSentiment: Neutral\nCluster: Venture capital fund winding up delay settlement', 'Mini Summary: Nilesh Shah, Managing Director of Kotak Mahindra Asset Management, is a panelist at the Mindmine Summit 2026.\nSentiment: Neutral\nCluster: Nilesh Shah attending Mindmine Summit 2026', 'Mini Summary: Kotak Mahindra Bank is listed as a provider of home loans with rates starting at 7.60%.\nSentiment: Positive\nCluster: Home loan interest rate offering', 'Mini Summary: Kotak Mahindra Bank is listed as a provider of home loans for women.\nSentiment: Positive\nCluster: Home Loan for women service listing', "Mini Summary: Kotak Mahindra AMC's Fixed Income Head Abhishek Bisen shares views on RBI's decision to keep the repo rate stable.\nSentiment: Neutral\nCluster: Fixed Income head shares RBI policy views", 'Mini Summary: Kotak Mahindra Bank reported one of the highest leverage ratios among Asia-Pacific banks.\nSentiment: Positive\nCluster: High leverage ratio in Asia-Pacific region', "Mini Summary: Kotak Mahindra Bank is acquiring Deutsche Bank's retail and wealth management business in India.\nSentiment: Positive\nCluster: Acquisition of retail and wealth business", 'Mini Summary: Kotak Mahindra Bank is offering FCNR(B) deposit rates between 6 per cent and 6.15 per cent.\nSentiment: Positive\nCluster: FCNR(B) deposit rates offered by bank', 'Mini Summary: Kotak Mahindra Bank is offering between 6 per cent and 6.15 per cent interest rates on FCNR(B) deposits.\nSentiment: Positive\nCluster: FCNR(B) deposit interest rates offered', 'Mini Summary: Kotak Mahindra Bank is offering interest rates between 6% and 6.15% on FCNR(B) deposits.\nSentiment: Positive\nCluster: FCNR(B) deposit interest rate offers', "Mini Summary: Kotak Mahindra Bank has entered a definitive agreement to acquire Deutsche Bank's retail, private banking, and wealth management business in India.\nSentiment: Positive\nCluster: Acquisition of retail and wealth management business", 'Mini Summary: Kotak Mahindra Bank is offering interest rates between 6% and 6.15% on FCNR(B) deposits for NRIs.\nSentiment: Positive\nCluster: FCNR(B) deposit interest rate offers', 'Mini Summary: Kotak Mahindra Bank is acquiring the retail, affluent private banking, and wealth management operations of Deutsche Bank in India.\nSentiment: Positive\nCluster: Acquisition of retail and wealth management business', 'Mini Summary: Kotak Mahindra Bank CEO Ashok Vaswani is stepping down from his leadership role.\nSentiment: Neutral\nCluster: CEO Ashok Vaswani stepping down', 'Mini Summary: Former Deputy VP Pushpinder Singh allegedly siphoned crores from Municipal Corporation accounts through fake bank accounts.\nSentiment: Negative\nCluster: Account fraud involving Pushpinder Singh', 'Mini Summary: Deputy VP Pushpinder Singh allegedly masterminded a 150 crore fraud by manipulating Municipal Corporation accounts.\nSentiment: Negative\nCluster: Pushpinder Singh manipulated Municipal Corporation accounts', 'Mini Summary: A senior bank executive is alleged to have used ₹33 crore of illicit funds to buy luxury assets through a fraud involving municipal corporation accounts.\nSentiment: Negative\nCluster: Pushpinder Singh misused municipal account funds', 'Mini Summary: Kotak Mahindra Bank is listed as a provider of home loans with interest rates starting from 7.60 percent.\nSentiment: Positive\nCluster: Home loan interest rates offered', 'Mini Summary: Tushar Verma, who previously held leadership roles at Kotak Mahindra Bank, has been appointed as VP at PeepalCo.\nSentiment: Neutral\nCluster: Tushar Verma former leadership role at bank', 'Mini Summary: Tushar Verma, who previously held senior positions at Kotak Mahindra Bank, has been appointed as VP of Banking and Institutional Business at PeepalCo.\nSentiment: Neutral\nCluster: Tushar Verma former employee appointment', 'Mini Summary: Kotak Mahindra Bank is offering interest rates between 6% and 6.15% on FCNR(B) deposits.\nSentiment: Positive\nCluster: FCNR(B) deposit interest rate offers', 'Mini Summary: Large cash withdrawals of ₹35 crore were made from Kotak Mahindra Bank within one month as part of a money laundering scheme.\nSentiment: Negative\nCluster: Account cash withdrawals for money laundering', 'Mini Summary: Nilesh Shah, Managing Director of Kotak Mahindra Asset Management, is a panelist at the Mindmine Summit 2026.\nSentiment: Neutral\nCluster: Nilesh Shah attending Mindmine Summit event', 'Mini Summary: Navrachana University graduates have secured placements at Kotak Bank.\nSentiment: Positive\nCluster: Bank hiring university graduates', 'Mini Summary: Navrachana University graduates have secured employment positions at Kotak Bank.\nSentiment: Positive\nCluster: Account employment placement for university graduates', 'Mini Summary: Nilesh Shah, Managing Director of Kotak Mahindra Asset Management, is a panelist at the Mindmine Summit 2026.\nSentiment: Neutral\nCluster: Nilesh Shah attending Mindmine Summit 2026', "Mini Summary: Graduates from Navrachana University's School of Business and Law have secured positions at Kotak Bank.\nSentiment: Positive\nCluster: Account placement of university graduates", "Mini Summary: Graduates from Navrachana University's School of Business and Law have secured placements at Kotak Bank.\nSentiment: Positive\nCluster: University graduates placed in Kotak Bank", 'Mini Summary: NCLT directed Kotak Mahindra Bank to release title deeds after the bank refused to do so despite full payment.\nSentiment: Negative\nCluster: Bank refused release of property title deeds', 'Mini Summary: Nilesh Shah, Managing Director of Kotak Mahindra Asset Management, is listed as a panelist for the Mindmine Summit 2026.\nSentiment: Neutral\nCluster: Kotak Mahindra AMC leader attending industry event', 'Mini Summary: Kotak Mahindra Bank is listed as one of the participating Indian banks for Nepal-India cross-border UPI transfers.\nSentiment: Positive\nCluster: UPI cross-border transfer service provider', "Mini Summary: Kotak Pay is listed among UPI applications required to implement NPCI's real-name verification rule.\nSentiment: Positive\nCluster: UPI app real-name verification feature", 'Mini Summary: Kotak Pay is listed as one of the bank-specific UPI apps that must comply with the new NPCI real-name verification rule.\nSentiment: Positive\nCluster: Kotak Pay named as UPI service provider', "Mini Summary: Kotak Pay is listed among UPI applications implementing NPCI's new real-name verification security rules.\nSentiment: Positive\nCluster: Kotak Pay named as UPI feature provider", 'Mini Summary: Kotak Mahindra Bank is listed as offering NRE fixed deposit rates between 7% and 7.5%.\nSentiment: Positive\nCluster: NRE Fixed Deposit interest rate offers', 'Mini Summary: Kotak Mahindra Bank challenged a debt restructuring arrangement in court, alleging its position was not considered.\nSentiment: Neutral\nCluster: Loan restructuring dispute in Karnataka High Court', 'Mini Summary: Kotak Mahindra Capital appointed as advisor for Bhagwati Products IPO.\nSentiment: Positive\nCluster: IPO advisory services for Bhagwati Products', 'Mini Summary: A woman lost ₹35,888 from her Kotak Mahindra Bank account via UPI transactions in a Telegram investment scam.\nSentiment: Negative\nCluster: UPI fraud via Kotak account', 'Mini Summary: Nilesh Shah, Managing Director of Kotak Mahindra Asset Management, is featured as a panelist at the Mindmine Summit 2026.\nSentiment: Neutral\nCluster: Asset Management leader attending industry summit', 'Mini Summary: Kotak Mahindra Bank provides instant cashback offers for OnePlus 13 purchases.\nSentiment: Positive\nCluster: Credit card cashback offers on OnePlus', 'Mini Summary: Kotak Mahindra Bank is offering an instant discount on the purchase of OnePlus 13.\nSentiment: Positive\nCluster: Credit card instant discount offers', 'Mini Summary: The text discusses Meta layoffs and the impact of AI on data science careers.\nSentiment: Neutral\nCluster: No banking product or incident mentioned.', 'Mini Summary: Kotak Mahindra Bank is offering an instant discount on the purchase of OnePlus 13.\nSentiment: Positive\nCluster: Credit card discount offers on OnePlus 13', 'Mini Summary: Kotak Mahindra Bank is offering an instant discount on the OnePlus Nord CE6.\nSentiment: Positive\nCluster: Credit card discount offers on OnePlus', 'Mini Summary: A customer lost Rs 99,000 from their Kotak Mahindra Bank account via UPI and Google Pay after clicking a phishing link.\nSentiment: Negative\nCluster: UPI fraud via phishing link account breach', 'Mini Summary: Palanisamy Annamalai previously served as Zonal Training Head at Kotak Mahindra Life Insurance.\nSentiment: Neutral\nCluster: Learning and development at Kotak Life Insurance', 'Mini Summary: ACB filed a chargesheet against nine individuals, including bank officials, for an alleged multi-crore embezzlement involving fake accounts and documents.\nSentiment: Negative\nCluster: Embezzlement via fake accounts and documents', 'Mini Summary: Tushar Verma, who previously held senior positions at Kotak Mahindra Bank, has been appointed as VP at PeepalCo.\nSentiment: Neutral\nCluster: Former employee joins PeepalCo as VP', 'Mini Summary: Kotak Mahindra Bank is planning CEO succession with Paritosh Kashyap and Anup Saha as potential internal candidates.\nSentiment: Positive\nCluster: Paritosh and Anup considered for CEO leadership', 'Mini Summary: Tushar Verma, who previously held senior positions at Kotak Mahindra Bank, has been appointed as VP at PeepalCo.\nSentiment: Neutral\nCluster: Tushar Verma previously held senior bank positions']

In [28]:
# Converting the list -> Pandas DataFrame
parsed_data = []
for line in result:
    item = line.split("\n")
    parsed_data.append(
        {
            "Summary" : item[0].replace("Mini Summary:",""),
            "Sentiment" : item[1].replace("Sentiment:",""),
            "Cluster" : item[2].replace("Cluster:","")
        }
    )
new_data = pd.DataFrame(parsed_data)
new_data.head()

,Summary,Sentiment,Cluster
0,Graduates from Navrachana University's School...,Positive,Placements at Kotak Bank
1,Kotak Mahindra Bank is offering interest rate...,Positive,FCNR(B) deposit interest rate offers
2,Kotak Mahindra Bank offers a Buy 1 Get 1 deal...,Positive,Cashback+ Credit Card movie ticket offers
3,Graduates from Navrachana University have sec...,Positive,Student placements in Kotak Bank
4,"Nilesh Shah, Managing Director of Kotak Mahin...",Neutral,Kotak Mahindra Asset Management executive att...